Fix Dockerfile and compose file to work with this source code and repo without cloning

diff --git a/docker/Dockerfile b/docker/Dockerfile
--- a/docker/Dockerfile
+++ b/docker/Dockerfile
@@ -1,24 +1,36 @@
 
-# Building
+### Building
 FROM haskell:9.10.1-buster as builder
 
+# Building dependencies
 WORKDIR /usr/src
-RUN git clone https://github.com/osklunds/HTTPImageServer.git
-WORKDIR /usr/src/HTTPImageServer
-RUN git checkout ce4829df11bff4bea44b87017f5692afe9efbae5
-RUN cabal update && \
-    cabal build --ghc-options="-fobject-code -O2"
+RUN cabal update
+COPY HTTPImageServer.cabal .
+RUN mkdir src
+# The below command will download and compile all dependencies, but then fail
+# hence the exit 0 at the end. This is a separate step so that source code
+# changes don't lead to recompiling dependencies which takes a long time.
+RUN cabal build --ghc-options="-fobject-code -O2" || exit 0
+
+# Building the source
+COPY src src
+COPY Test Test
+COPY html html
+RUN ls
+RUN cabal build --ghc-options="-fobject-code -O2"
 
 # Workaround since project incorrectly assumes cwd, meaning cabal install
 # doesn't work
 RUN cd dist-newstyle/build/*/ghc-9.10.1/HTTPImageServer-0.1.0.0/x/HTTPImageServer/build/HTTPImageServer && cp HTTPImageServer /usr/src/HTTPImageServer.bin
  
+### The actual image
 FROM debian:bookworm-slim
+
 COPY --from=builder /usr/src/HTTPImageServer.bin /usr/local/bin/HTTPImageServer
-RUN apt-get update -y && apt-get install -y curl
-COPY run.sh .
-COPY healthcheck.sh .
-COPY common.sh .
+RUN apt-get update -y && apt-get install -y curl libpcre3 libpcre3-dev
+COPY docker/run.sh .
+COPY docker/healthcheck.sh .
+COPY docker/common.sh .
 CMD ["./run.sh"]
 
 HEALTHCHECK CMD "./healthcheck.sh"
